version = "1.0"

[main]
name.en = "Readeck configuration"
name.fr = "Configuration de Readeck"
services = ["__APP__"]


    [main.configuration]

        [main.configuration.public_share_ttl]
        ask.en = "Public link sharing lifetime"
        ask.fr = "Temps validité des liens partagés"
        type = "number"
        help.en = "Indicate the public link sharing lifetime, in hours"
        help.fr = "Indiquer le temps de validité des liens partagés, en heures"
        bind = "public_share_ttl:__DATA_DIR__/config.toml"
