#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "readeck"
name = "Readeck"
description.en = "Bookmark manager and a read later tool"
description.fr = "Gestionnaire de favoris et outil de lecture ultérieure"

version = "0.22.1~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0"
website = "https://readeck.org/"
admindoc = "https://readeck.org/en/docs/"
code = "https://codeberg.org/readeck/readeck"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    i386.url = "https://codeberg.org/readeck/readeck/releases/download/0.22.1/readeck-0.22.1-linux-386"
    i386.sha256 = "6d62c521bae19859aedcdb7bb9084284099d58bf38c3d89516498a0fb2ec7c34"
    amd64.url = "https://codeberg.org/readeck/readeck/releases/download/0.22.1/readeck-0.22.1-linux-amd64"
    amd64.sha256 = "cfb67aa6ed75b935393fe35ea3bd36528d12be1786419741125f9ffbda268aae"
    arm64.url = "https://codeberg.org/readeck/readeck/releases/download/0.22.1/readeck-0.22.1-linux-arm64"
    arm64.sha256 = "1529b904f309250d0ad056f5bd77fa477a0322ba04fc3cf780c64b9a9f24f945"
    armhf.url = "https://codeberg.org/readeck/readeck/releases/download/0.22.1/readeck-0.22.1-linux-arm-5"
    armhf.sha256 = "968665f495fbbec80aef8acf2161305e92783e161170a1227d75ac8f8132124f"
    rename = "readeck"

    autoupdate.strategy = "latest_forgejo_release"
    autoupdate.asset.i386 = "^readeck-.*-linux-386$"
    autoupdate.asset.amd64 = "^readeck-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^readeck-.*-linux-arm64$"
    autoupdate.asset.armhf = "^readeck-.*-linux-arm-5$"
    
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.auth_header = false

    opds.url = "/opds"
    opds.allowed = "visitors"
    opds.show_tile = false
    opds.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
