[main]
log_level = "info"
secret_key = "__SECRET_KEY__"
data_directory = "__DATA_DIR__"

[server]
host = "127.0.0.1"
port = __PORT__
allowed_hosts = ["__DOMAIN__"]
trusted_proxies = ["127.0.0.1"]

[database]
source = "postgres://__DB_USER__:__DB_PWD__@localhost:5432/__DB_NAME__"

[email]
host = "__DOMAIN__"
port = 587
username = "__APP__"
password = "__MAIL_PWD__"
encryption = "starttls"
from = "__APP__@__DOMAIN__"
#`allow_email` only creates a single email address on the domain, 
# we don't have a specific "no-reply" one, so let's reuse it 
from_noreply = "__APP__@__DOMAIN__"

[bookmarks]
# please use the YunoHost config panel to edit this setting
# otherwise your edition will be rest at each update of the package
public_share_ttl = __PUBLIC_SHARE_TTL__
